name: meditation_companion
description: "An interactive meditation app that transforms your meditation practice through personalized real-time guidance and adaptive feedback."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.0
  equatable: ^2.0.5
  supabase_flutter: ^2.3.4
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  test: ^1.24.9
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.0

flutter:
  uses-material-design: true
