name: meditation_companion
description: Meditation companion app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  supabase_flutter: ^2.9.0
  flutter_soloud: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  test: ^1.25.8

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
